name: Continuous deployment

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FONTAWESOME_NPM_TOKEN: ${{ secrets.FONTAWESOME_NPM_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Remove old now bin
        run: sudo rm /usr/local/bin/now

      - name: Deploy to now
        run: npx now@latest -c --prod -t ${{ secrets.NOW_TOKEN }}
